[package]
name = "grafen"
<<<<<<< HEAD
version = "0.10.0"
=======
version = "0.10.1-dev"
>>>>>>> development
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create graphene and other substrates for use in molecular dynamics simulations."
repository = "https://github.com/pjohansson/grafen"
documentation = "https://docs.rs/crate/grafen"
categories = ["command-line-utilities", "science"]
keywords = ["gromacs", "molecular-dynamics", "substrates"]
readme = "README.md"
license = "Unlicense"

[badges]
travis-ci = { repository = "pjohansson/grafen", branch = "master" }

[dependencies]
bitflags = "1.0"
colored = "1.6"
dialoguer = "0.1"
mdio = { git = "https://github.com/pjohansson/mdio" }
rand = "~0.3.0"
serde = "^1.0.8"
serde_json = "1.0"
serde_derive = "^1.0.8"
structopt = "0.2"
structopt-derive = "0.2"

[[bin]]
path = "src/bin/main.rs"
name = "grafen"
doc = false
